eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
spring:
  datasource:
    name: test
    url: jdbc:mysql://218.18.161.41:6000/dsfsfsf?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root1234
    # 使用druid数据源
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 0
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 50
      keepAliveSeconds: 300
      queueCapacity: 1000

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:com/mapping/module/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.*.module.*.bean  # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
#配置fastDFS
fdfs:
  trackerList: 
    - 218.18.161.41:7301

#配置Redis
redis:
  blockWhenExhausted: true
  host: 218.18.161.41
  maxIdle: 300
  maxTotal: 500
  maxWaitMillis: 3000
  minIdle: 100
  password: we@123456
  port: 6379
  testOnBorrow: true
  timeout: 2000
  
 #日志配置
logging:
  level: 
    com.webuilding.module: debug
    
#线程池    
threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 300
